### ISSUE TITLE
Mid-shower PN Biasing

### ISSUE THREAD

**Issue by omar-moreno** [LDMX-Software/ldmx-sw#523]

**Comment by tomeichlersmith** [comment]
Issue #800  will probably be helpful if I can get that working. I'm thinking we can focus on a filter that aborts the event if a high enough energy photon _doesn't_ undergo PN and then pair that with a biasing operator that biases all photons above a certain energy to go PN.

This energy threshold would need to be determined by a study of inclusive samples to see what amount going PN actually matters.

Another option (without Issue #800 ) is to use the idea of "generations" of particles that I used for the DarkBremFilter on the `eat` branch. This counts the number of generations since the primary and filters on "generations" instead of particle energy. This would probably be less efficient, but it would work almost out-of-the-box since I got it working for the signal process.

**Comment by tomeichlersmith** [comment]
I have now implemented a partial energy sorter on the EaT developments branch (PR #918 ), and have started using it for biasing the signal process. I think this means we will be able to (somewhat) easily translate its use for other processes.

**Comment by tomeichlersmith** [comment]
I am closing this issue since the EaT developments #953 have given us the tools to study midshower PN+EN. While the example config in `trunk` is for the EaT analysis channel, this config can be modified pretty easily to focus on hard-brem in target + midshower nuclear in ECal.
