### ISSUE TITLE
ECal Layer Shifting and incorporate layerID in ECalHexReadout

### ISSUE THREAD

**Issue by Hongyin-bug** [LDMX-Software/ldmx-sw#904]
**Is your feature request related to a problem? Please describe.**
Layer-shift the second layer within each bi-layer of Ecal layers--- to cover cracks.
ECalHexReadout is a x-y map of cells, but does not describe how x and y changes with z.
ECalID.h has layers defined in terms of double layers (i.e. 17 layers with 12 ring modules in a layer)--- not convenient for layer shifting (need to separately define 34 layers)

**Describe the solution you'd like**
Need to add layerID and incorporate z as a function of x-y in ECalHexReadout.h and .cxx.
Add Layer shifting in ECalHexReadout.
Change ECalID so that there are 34 layers and 6 ring modules in each.

**Describe alternatives you've considered**
Link the ecal.gdml file to ECalHexReadout so that it's not necessary to change ECalHexReadout every time a new layer-configuration is tried out?

**Additional context**
![layer-shift](https://user-images.githubusercontent.com/57277920/92353112-73644a80-f094-11ea-9ae1-0dd9aff1f706.png)
![One module layer-shift](https://user-images.githubusercontent.com/57277920/92419309-9ee14680-f121-11ea-87a0-1bd427d82977.png)

**Comment by jmmans** [comment]
Dear Hongyin,

EcalID doesn't know how many layers there are, it is simply a container 
for values passed in to it.  The assignment of layer numbers is done in 
EcalHexReadout as used in the simulation code.

I agree with the idea that each actual layer should be separate in the 
code, so if it's true that we have double layers in there now, it would 
make sense to change it.  This will break a lot of things, however, so 
it cannot be done in the mainline until a future major release.  It 
would be reasonable to pursue as a branch development until then.

Regarding the GDML and EcalHexReadout issue -- this is a brittle 
connection because the GDML is only loaded when an actual simulation job 
is run.  If the digis are stored and then loaded back off disk, the GDML 
isn't loaded.  Instead, EcalHexReadout needs to know what to do 
_without_ the GDML available.  Therefore, the necessary information 
would need, for example, to be put into the RunHeader.  It could be 
sourced from the GDML.  Detailed proposals of what information is 
sufficient would be valuable.

J. Mans

**Comment by Hongyin-debug** [comment]
Hi Jeremiah,
I see! Yes, the ECal ID has container values of up to 17 layers.
In the original ECalHexReadout, the position map of the modules are in terms of x-y, so every layer is a copy of the x-y map of the first layer (or zeroth layer).  So in the original ECalHexReadout, there isn't really an assignment of layers numbers in terms of double layers, it's just it doesn't have each layer (or double layer) uniquely defined at all. 
So originally, the key value for modulePositionMap_ only has moduleID, I'm thinking of changing it to a pair as key (<layer ID, moduleID>), and adding some z positions in ECalHexReadout.
The branch iss904 focuses on this issue, but it's still in progress. I'll send around a message when I think it's ready for double-checking.
The branch I'm currently working on has the layer shifting incorporated, do you think it's necessary to start a separate branch just for adding layerID into ECalHexReadout without the layer shifting?
-Hongyin

**Comment by tomeichlersmith** [comment]
Hi Hongyin,
I'm not sure if your interpretation of the IDs is correct. How are you determining the maximum is 17? The layer and module IDs are decoded from the copy number in ecal.gdml as described [in this document](https://www.overleaf.com/read/hfhrgtyftykd).

Another suggestion I have is to avoid creating another data structure. you could use `EcalID(layerID,moduleID,0)` to be the key in your module position map instead of a new combination of of layer and module IDs. This is what we do for the "flattened" map where we don't include the layer ID, so you could think of this as another "flattening" in the "cell ID" axis.

Lastly, I don't think that it is necessary to have a separate branch for adding the layer ID into EcalHexReadout without the layer shifting. As long as you can set the layer shift to zero (and recover the original layout) at run time (using python configuration variables).
Tom

**Comment by Hongyin-debug** [comment]
Hi Tom,
Yes, everything seems fine in ecal.gdml. For ECalID.h though, it shows:
	static const RawValue LAYER_MASK{0x3F}; // space for up to 64 layers
	static const RawValue LAYER_SHIFT{17};
	static const RawValue MODULE_MASK{0x1F}; // space for up to 32 modules/layer
	static const RawValue MODULE_SHIFT{12};
I'm thinking of changing it to:
	static const RawValue LAYER_MASK{0x3F}; // space for up to 64 layers
	static const RawValue LAYER_SHIFT{34};
	static const RawValue MODULE_MASK{0x1F}; // space for up to 32 modules/layer
	static const RawValue MODULE_SHIFT{7};
I'm not sure if this will affect the other files much, but I'm guessing not?

And yes, it is a good idea to use instead EcalID(layerID,moduleID,0) as key since it would already include both layerID and moduleID.

I see, yes, the layer shift value is easy to set :D 
Hongyin

**Comment by jmmans** [comment]
Dear Hongyin,

This MUST NOT BE CHANGED.  It will horribly break data on disk.

The "LAYER_SHIFT" has nothing to do with the number of layers allowed. 
It has to do with how the 32-bit unsigned integer is decoded.

To get the layer out of the id, you take the 32-bit integer, shift it 
right by 17 bits and then apply an AND mask to it to select the bottom 
six bits.  This is all done internally.

Notice the comment -- we can store up to 64 layers, 32  modules/layer, 
etc.  This is to allow for possible future studies.  In _reality_, the 
id current is used up to 34 layers, 7 modules per layer.

Jeremy

**Comment by Hongyin-debug** [comment]
Hi Jeremiah,
That makes sense!
-Hongyin

**Comment by Hongyin-debug** [comment]
The submodules for this issue can be found here:
Ecal: https://github.com/LDMX-Software/Ecal/tree/iss904
SimCore: https://github.com/LDMX-Software/SimCore/tree/iss904

**Comment by hongyin-liu** [comment]
A new branch iss904-rotate has been set up for the rotated Ecal geometry.
The main changes are in EcalHexReadout.cxx,  EcalHexReadout.h, and Ecal.gdml.
Submodules: 
Ecal: https://github.com/LDMX-Software/Ecal/tree/iss904-rotate
SimCore: https://github.com/LDMX-Software/SimCore/tree/iss904-rotate

A rough overview: [Ecal Rotation.pdf](https://github.com/LDMX-Software/ldmx-sw/files/5880463/Ecal.Rotation.pdf)
A more detailed explanation (includes technical details): 
[ldmx-sw changes Ecal Rotation.pdf](https://github.com/LDMX-Software/ldmx-sw/files/5964584/ldmx-sw.changes.Ecal.Rotation.pdf)

**Update: Ignore the cell maps in the above slides, below are the most updated rotated cell maps (cell map, trigger cell map, uv cell map):
![Cell_ID_Cell_Position_Map_new](https://user-images.githubusercontent.com/57277920/108492841-7cb82c80-725a-11eb-9f6b-c482795e41e1.png)
![TriggerCell_Position_Map_new](https://user-images.githubusercontent.com/57277920/108492856-804bb380-725a-11eb-8245-1617890902a3.png)
![Cell_UV_Cell_Position_Map_new](https://user-images.githubusercontent.com/57277920/108492867-8346a400-725a-11eb-84cc-4dbf3cf77600.png)
Here are two slides comparing the old and new cell maps:
[Cell_maps_old.pdf](https://github.com/LDMX-Software/ldmx-sw/files/6009266/Cell_maps_old.pdf)
[Cell_maps_new.pdf](https://github.com/LDMX-Software/ldmx-sw/files/6009267/Cell_maps_new.pdf)
