### ISSUE TITLE
Allow setting of log level for a processor

### ISSUE THREAD

**Issue by omar-moreno** [LDMX-Software/ldmx-sw#922]
**Is your feature request related to a problem? Please describe.**
Currently, the log level can only be set globally.  This is an issue when trying to debug a processor because messages from all other processors are also printed.  It would be useful to set the log level such that it only applies to a given processor.

**Comment by tomeichlersmith** [comment]
@bryngemark I can handle the core framework stuff and loop you in after that is completed. I won't start on this until after the structural changes for v3.0.0 go in.

**Comment by bryngemark** [comment]
@tomeichlersmith Sounds good!

**Comment by tomeichlersmith** [comment]
https://github.com/LDMX-Software/ldmx-sw/issues/1409#issuecomment-2311040238

**Comment by tomeichlersmith** [comment]
This is related to #1301 - in the sense that both would touch the same code files.

I would also be interested in moving `logging::open` as early as possible, specifically before any of the processors are created so that the `ldmx_log` messages are directed to the file/terminal as configured. Right now, `logging::open` doesn't happen until after the processors are `configure`d which means the logging messages in `configure` overrides are not formatted the same way and are not directed to a log file if one is specified.
